apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gqry6whvu-java-springboot
  janus-idp.io/tekton: gqry6whvu-java-springboot
  backstage.io/kubernetes-id: gqry6whvu-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gqry6whvu-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
